# <center><b>Week-5 Python Programming</b></center>
## <center><b>Numpy Continuation</b></center>
### <center><i><u>Author: Ujjwal Karki</u></i></center>

## Reshaping 1,6 array to 2x3 array

In [1]:
# Reshaping 1,6 array to 2,3 array
import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = arr.reshape(2,3)

print("Original array:\n", arr)
print("------------------")
print("Reshaped array:\n", newarr)  

Original array:
 [1 2 3 4 5 6]
------------------
Reshaped array:
 [[1 2 3]
 [4 5 6]]


### Flatten array
- Flatten method flattens array to one dimensional and returns copy of collapsed array

In [4]:
# Flatten array 
arr = np.array([[1,2,3],[4,5,6]])

fltarr = arr.flatten()
print(arr)
print("---------")
print(fltarr)

[[1 2 3]
 [4 5 6]]
---------
[1 2 3 4 5 6]


### Numpy Array indexing and slicing

<br><b>Basic indexing</b><br>
Indexing allow us to access the individual elements or subsets of data

In [ ]:
# 1D array indexing

arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr[0])  # prints 1
print(arr[-1])  # last element
print(arr[3])  # fourth element

# 2D array indexing
num_2d_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print("Print dimension of array: ")
print(num_2d_array.ndim) # prints the dimension of the array
print("Shape of the array: ")
print(num_2d_array.shape) # prints the shape of the array
print("Total items of the array: ")
print(num_2d_array.size) # prints the total number of the array

print("first row first element")
print(num_2d_array[0,0])
print("second row last element")
print(num_2d_array[1,-1])
print("last row last element")
print(num_2d_array[-1,-1])
print("third row second element")
print(num_2d_array[-1,1])


(6,)
1
6
4
Print dimension of array: 
2
Shape of the array: 
(3, 3)
Total items of the array: 
9
first row first element
1
second row last element
6
last row last element
9


### Slicing numpy
In numpy we can access the portion of an array using the slice operator ``:``

### 1D array slicing
Syntax: ``array[start:stop:step]``
- ``start``: index of the first element to be included in slice
- ``stop``: index of the last element (exclusive) 
- ``step``: index of the slice between each element in slice


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])

# slicing array from index 2-6 6(exclusive)
print(arr[2:6])
print("-----------------")

# slicing array from 0 to 8 with a step size of 2
print(arr[0:8:2])
print("-----------------")
# slicing array from 4 to last element

print(arr[4:])
print("-----------------")

print(arr[::2])
print("-----------------")

# negative index
print(arr[-1::-2])
print("-----------------")

# we can also modify the array with slicing

arr[:5] = 100 # replace items from 0-5 with 100
print(arr)

[3 4 5 6]
-----------------
[1 3 5 7]
-----------------
[5 6 7 8]
-----------------
[1 3 5 7]
-----------------
[8 6 4 2]
-----------------
[100 100 100 100 100   6   7   8]


# 2-D array slicing

syntax: ```array[row_start:row_stop:row_step, col_start:col_stop:col_step]```

In [13]:
array2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(array2d.ndim)

# slicing first row
print(array2d[0:2,0:2])



2
[[1 2]
 [4 5]]


### Boolean array indexing

Boolean array indexing allows us to select elements from an array based on conditions. This technique is helpful when we need to filter elements based on certain condition.

In [ ]:
# Creating an array
arr = np.array([5,10,15,20,25,30])

# Select elements greater than 15
print(arr[arr>15])

# Select elements that are even
print(arr[arr % 2 == 0])

# Modify elements that satisfy a condition
arr[arr > 15] = 99
print(arr)

# Boolean indexing on a 2-dimensional array
array2d = np.array([[1,2,3],[4,5,6]])

# Extract elements greater than 4
print(array2d[array2d>2]) # Returns one D output

# Selecting elements greater than 4 to zero
array2d[array2d>4] = 0 # Returns 2D output as we are just changing the values
print(array2d)


[20 25 30]
[10 20 30]
[ 5 10 15 99 99 99]
[3 4 5 6]
[[1 2 3]
 [4 0 0]]


### Numpy operations
- Numpy arithmetic array operations
- Numpy array functions
- Numpy comparison/logical functions
- Numpy math functions
- Numpy constants
- Numpy statistical functions

#### Numpy arithmetic array operations
- add()
- subtract()
- multiply()
- divide()
- power()
- mod()

In [27]:
first_array = np.array([1,2,3])
second_array = np.array([4,5,6])

add_array = np.add(first_array,second_array)
print("Add: ",add_array)

sub_array = np.subtract(second_array,first_array)
print("Subtract: ",sub_array)

mul_array = np.multiply(first_array,second_array)
print("Mul: ",mul_array)

divide_array = np.divide(first_array,second_array)
print("Div: ",divide_array)

power_array = np.power(first_array,second_array)
print("Power: ",power_array)

mod_array = np.mod(second_array,first_array)
print("Mod: ",mod_array)


Add:  [5 7 9]
Subtract:  [3 3 3]
Mul:  [ 4 10 18]
Div:  [0.25 0.4  0.5 ]
Power:  [  1  32 729]
Mod:  [0 1 0]


### Numpy broadcasting
- Broadcasting in numpy allows it to perform arithmetic operations on arrays with different sizes

In [ ]:
firsts_array = np.array([1,2,3,4])
temp_array = np.array([1,4,5,6])

# result = 
print(firsts_array * temp_array)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 